name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make build dir
      run: mkdir build
    - name: submodules
      run: git submodule update --init --recursive
    - name: make lexer
      run: make build/lexer
    - name: make filter_ok
      run: make build/filter_ok
    - name: make ulci
      run: make build/ulci
    - name: utests
      run: ./build/utests
    - name: itests
      run: ./build/itests
    
