name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make build dir
      run: mkdir build
    - name: submodules
      run: git submodule update --init --recursive
    - name: make 
      run: make build/interpreter build/itests
    - name: itests
      run: ./build/itests
    
